receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    limit_mib: 512
    check_interval: 1s
    spike_limit_mib: 128

connectors:
  flowmetrics:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 500

  prometheus:
    endpoint: "0.0.0.0:8887"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [flowmetrics]
    
    metrics:
      receivers: [flowmetrics]
      processors: []
      exporters: [prometheus, debug]

  telemetry:
    logs:
      level: info
      output_paths: ["collector.log", "stdout"]
    metrics:
      level: detailed